//! The peephole's local rewrites: one matcher per group of `peephole.peep`,
//! generated by build.rs, and the walks, guards and makers they call.

pub mod guards;
pub mod make;
pub mod walk;

use std::sync::Arc;

use llrm_lir::registers::RegId;

use crate::model::lir::{Insn, LirBody};

/// A set of mnemonics from `peephole.peep`, and for a family (`far_loads`)
/// the fixed register that picks each member.
pub struct Set {
    pub names: &'static [&'static str],
    pub fixed: &'static [(RegId, &'static str)],
}

impl Set {
    pub fn contains(
        &self,
        name: &str,
    ) -> bool {
        self.names.contains(&name)
    }

    pub fn by_fixed(
        &self,
        register: RegId,
    ) -> Option<&'static str> {
        self.fixed.iter().find(|(one, _)| *one == register).map(|(_, name)| *name)
    }
}

/// The metadata `guards::free` can require empty, one bit each.
pub mod field {
    pub const CLOBBERS: u32 = 1 << 0;
    pub const CLOBBERS_HIGH: u32 = 1 << 1;
    pub const REQUIRES: u32 = 1 << 2;
    pub const DELIVERS: u32 = 1 << 3;
    pub const SPREAD: u32 = 1 << 4;
    pub const GROUP: u32 = 1 << 5;
    /// `symbol` is not `Some(true)`.
    pub const SYMBOL: u32 = 1 << 6;
    pub const FRAME_ADJUST: u32 = 1 << 7;
    pub const SPILL_RELOAD: u32 = 1 << 8;
    pub const SPILL_STORE: u32 = 1 << 9;
    pub const DEFINES: u32 = 1 << 10;
    pub const USES: u32 = 1 << 11;
    /// `covers` is one point: the instruction owns no source bytes.
    pub const POINT: u32 = 1 << 12;
    /// `covers` is no range: absent or one point.
    pub const UNOWNED: u32 = 1 << 13;
    /// `volatile` is false.
    pub const VOLATILE: u32 = 1 << 14;
}

/// A rewrite of a whole body by one rule group.
pub type BodyRule = fn(&LirBody, &walk::Facts) -> LirBody;
/// A rewrite of a run of instructions by one rule group.
pub type InsnRule = fn(&[Arc<Insn>], &walk::Facts) -> Vec<Arc<Insn>>;

/// `body` rewritten by `rule`, unchanged where the target has none.
pub fn rewritten(
    rule: Option<BodyRule>,
    body: &LirBody,
    facts: &walk::Facts,
) -> LirBody {
    rule.map_or_else(|| body.clone(), |rule| rule(body, facts))
}

/// `insns` rewritten by `rule`, unchanged where the target has none.
pub fn rewritten_insns(
    rule: Option<InsnRule>,
    insns: &[Arc<Insn>],
    facts: &walk::Facts,
) -> Vec<Arc<Insn>> {
    rule.map_or_else(|| insns.to_vec(), |rule| rule(insns, facts))
}

/// No mnemonics.
pub static NO_NAMES: Set = Set { names: &[], fixed: &[] };

include!(concat!(env!("OUT_DIR"), "/peep_rules.rs"));

#[cfg(test)]
mod tests;
