//! The peephole's local rewrites: one matcher per group of `peephole.peep`,
//! generated by build.rs, and the walks, guards and makers they call.

pub mod guards;
pub mod make;
pub mod walk;

use std::sync::Arc;

use iced_x86::Register;

use crate::model::lir::{Insn, LirBody};

/// A set of mnemonics from `peephole.peep`, and for a family (`far_loads`)
/// the fixed register that picks each member.
pub struct Set {
    pub names: &'static [&'static str],
    pub fixed: &'static [(Register, &'static str)],
}

impl Set {
    pub fn contains(&self, name: &str) -> bool {
        self.names.contains(&name)
    }

    pub fn by_fixed(&self, register: Register) -> Option<&'static str> {
        self.fixed.iter().find(|(one, _)| *one == register).map(|(_, name)| *name)
    }
}

/// The metadata `guards::free` can require empty, one bit each.
pub mod field {
    pub const CLOBBERS: u32 = 1 << 0;
    pub const CLOBBERS_HIGH: u32 = 1 << 1;
    pub const REQUIRES: u32 = 1 << 2;
    pub const DELIVERS: u32 = 1 << 3;
    pub const SPREAD: u32 = 1 << 4;
    pub const GROUP: u32 = 1 << 5;
    /// `symbol` is not `Some(true)`.
    pub const SYMBOL: u32 = 1 << 6;
    pub const FRAME_ADJUST: u32 = 1 << 7;
    pub const SPILL_RELOAD: u32 = 1 << 8;
    pub const SPILL_STORE: u32 = 1 << 9;
    pub const DEFINES: u32 = 1 << 10;
    pub const USES: u32 = 1 << 11;
    /// `covers` is one point: the instruction owns no source bytes.
    pub const POINT: u32 = 1 << 12;
    /// `covers` is no range: absent or one point.
    pub const UNOWNED: u32 = 1 << 13;
    /// `volatile` is false.
    pub const VOLATILE: u32 = 1 << 14;
}

/// A rewrite of a whole body by one rule group.
pub type BodyRule = fn(&LirBody, &walk::Facts) -> LirBody;
/// A rewrite of a run of instructions by one rule group.
pub type InsnRule = fn(&[Arc<Insn>], &walk::Facts) -> Vec<Arc<Insn>>;

/// `body` rewritten by `rule`, unchanged where the target has none.
pub fn rewritten(rule: Option<BodyRule>, body: &LirBody, facts: &walk::Facts) -> LirBody {
    rule.map_or_else(|| body.clone(), |rule| rule(body, facts))
}

/// `insns` rewritten by `rule`, unchanged where the target has none.
pub fn rewritten_insns(rule: Option<InsnRule>, insns: &[Arc<Insn>], facts: &walk::Facts) -> Vec<Arc<Insn>> {
    rule.map_or_else(|| insns.to_vec(), |rule| rule(insns, facts))
}

/// No mnemonics.
pub static NO_NAMES: Set = Set { names: &[], fixed: &[] };

/// What a target's `peephole.peep` made: each rule group, or none where the
/// target has no such group. Bound to a target by `llrm-driver` through its
/// selector.
pub struct Rules {
    pub extensions: Option<BodyRule>,
    pub extensions_insns: Option<InsnRule>,
    pub pushed_constants: Option<BodyRule>,
    pub pushed_constants_insns: Option<InsnRule>,
    pub pushes: Option<BodyRule>,
    pub pushes_insns: Option<InsnRule>,
    pub narrowed_moves: Option<BodyRule>,
    pub narrowed_moves_insns: Option<InsnRule>,
    pub commuted: Option<BodyRule>,
    pub commuted_insns: Option<InsnRule>,
    pub transferred: Option<BodyRule>,
    pub transferred_insns: Option<InsnRule>,
    pub shuttles: Option<BodyRule>,
    pub shuttles_insns: Option<InsnRule>,
    pub restored_copies: Option<BodyRule>,
    pub restored_copies_insns: Option<InsnRule>,
    pub fused: Option<BodyRule>,
    pub fused_insns: Option<InsnRule>,
    pub far_loads: Option<BodyRule>,
    pub far_loads_insns: Option<InsnRule>,
    pub increments: Option<BodyRule>,
    pub increments_insns: Option<InsnRule>,
    pub borrows: Option<BodyRule>,
    pub borrows_insns: Option<InsnRule>,
    pub doubled: Option<BodyRule>,
    pub doubled_insns: Option<InsnRule>,
    pub zero_compares: Option<BodyRule>,
    pub zero_compares_insns: Option<InsnRule>,
    pub memory_arguments: Option<BodyRule>,
    pub memory_arguments_insns: Option<InsnRule>,
    pub paired_pushes: Option<BodyRule>,
    pub paired_pushes_insns: Option<InsnRule>,
    pub immediate_arguments: Option<BodyRule>,
    pub immediate_arguments_insns: Option<InsnRule>,
    /// The conditional jumps that test only a zero or a sign.
    pub zero_jcc: &'static Set,
}

impl Rules {
    /// A target with no peephole rules.
    pub const NONE: Rules = Rules {
        extensions: None,
        extensions_insns: None,
        pushed_constants: None,
        pushed_constants_insns: None,
        pushes: None,
        pushes_insns: None,
        narrowed_moves: None,
        narrowed_moves_insns: None,
        commuted: None,
        commuted_insns: None,
        transferred: None,
        transferred_insns: None,
        shuttles: None,
        shuttles_insns: None,
        restored_copies: None,
        restored_copies_insns: None,
        fused: None,
        fused_insns: None,
        far_loads: None,
        far_loads_insns: None,
        increments: None,
        increments_insns: None,
        borrows: None,
        borrows_insns: None,
        doubled: None,
        doubled_insns: None,
        zero_compares: None,
        zero_compares_insns: None,
        memory_arguments: None,
        memory_arguments_insns: None,
        paired_pushes: None,
        paired_pushes_insns: None,
        immediate_arguments: None,
        immediate_arguments_insns: None,
        zero_jcc: &NO_NAMES,
    };
}

/// Every target's rules, as its definition directory is named.
pub mod targets {
    include!(concat!(env!("OUT_DIR"), "/peep_targets.rs"));
}

#[cfg(test)]
mod tests;
