//! The registers and flags an instruction reads and writes, as `x86.instr` states them (generated by `build.rs`), for
//! the target of `bits`-bit code.

use llrm_x86_m16::instructions::effects as table;
pub use table::{Effects, Served};

use crate::model::ir::Semantics;

mod rows {
    include!(concat!(env!("OUT_DIR"), "/effects.rs"));
}

/// What the table says of `what`, or None where it has no row (the instruction is then decoded).
pub fn served(
    bits: u32,
    what: &Semantics,
) -> Option<Served> {
    match bits {
        16 => table::effects(&rows::x86_m16::rows, bits, what),
        32 => table::effects(&rows::x86_m32::rows, bits, what),
        _ => None,
    }
}
