//! The registers and flags an instruction reads and writes, as `x86.instr`
//! states them (generated by a target's select crate), for the target whose
//! code is `bits` bits.

use std::sync::OnceLock;

pub use llrm_x86::effects::{Effects, Served};

use crate::model::ir::Semantics;

/// A target's rows of `name` with `dests` destinations and `sources` sources.
pub type Rows = fn(&str, usize, usize) -> &'static [llrm_x86::effects::Row];

/// The rows of the targets bound so far, by code width: 16, 32 and 64.
static TABLES: [OnceLock<Rows>; 3] = [OnceLock::new(), OnceLock::new(), OnceLock::new()];

fn slot(bits: u32) -> Option<&'static OnceLock<Rows>> {
    match bits {
        16 => Some(&TABLES[0]),
        32 => Some(&TABLES[1]),
        64 => Some(&TABLES[2]),
        _ => None,
    }
}

/// Binds `rows` to the code width `bits` (the driver does this for a target
/// when it binds its selector); the first binding stands.
pub fn register(
    bits: u32,
    rows: Rows,
) {
    if let Some(slot) = slot(bits) {
        let _ = slot.set(rows);
    }
}

#[cfg(feature = "fixtures")]
mod fixtures {
    include!(concat!(env!("OUT_DIR"), "/effects.rs"));
}

fn rows_for(bits: u32) -> Option<Rows> {
    if let Some(rows) = slot(bits).and_then(|slot| slot.get()) {
        return Some(*rows);
    }
    #[cfg(feature = "fixtures")]
    if let Some(rows) = fixtures::rows_for(bits) {
        return Some(rows);
    }
    None
}

/// What the table says of `what`, or None where it has no row (the instruction
/// is then decoded).
pub fn served(
    bits: u32,
    what: &Semantics,
) -> Option<Served> {
    llrm_x86::effects::effects(&rows_for(bits)?, bits, what)
}
