//! The registers and flags an instruction reads and writes, as `x86.instr`
//! states them (generated by `build.rs`), for the target whose code is `bits`
//! bits.

pub use llrm_x86::effects::{Effects, Served};

use crate::model::ir::Semantics;

mod rows {
    include!(concat!(env!("OUT_DIR"), "/effects.rs"));
}

/// What the table says of `what`, or None where it has no row (the instruction
/// is then decoded).
pub fn served(
    bits: u32,
    what: &Semantics,
) -> Option<Served> {
    llrm_x86::effects::effects(rows::rows_for(bits)?, bits, what)
}
