[portable]
sources = ["runtime.c"]

exports = ["B$CEND", "B$CENP", "B$CLOS", "B$DDIM", "B$DSG0", "B$ENRA", "B$ERAS", "B$EXSA", "B$FLOF", "B$GET3", "B$LTRM", "B$OPEN", "B$PESD", "B$SASS", "B$SPAC", "B$STDL", "B$STI4", "b$seg"]

[platform]
sources = [
  "platform/qb/dos/m16/start.asm",
  "platform/qb/dos/m16/frame.asm",
  "platform/qb/dos/m16/string_abi.asm",
  "platform/qb/dos/m16/text.asm",
  "platform/qb/dos/m16/array_abi.asm",
  "platform/qb/dos/m16/file_abi.asm",
]

[shared]
sources = ["runtime/shared/dos/m16/os.asm"]
