[package]
name = "llrm-bc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The BC object frontend: machine code raised onto llrm-mir"

[dependencies]
llrm-bcmachine = { workspace = true }
llrm-target = { workspace = true }
llrm-qbruntime = { workspace = true }
llrm-mir = { workspace = true }
llrm-analysis = { workspace = true }
llrm-hir = { workspace = true }
llrm-x86-m16 = { workspace = true }
iced-x86 = { workspace = true }

[dev-dependencies]
llrm-omf = { workspace = true }
