//! Ports of `qbopt/backend`.

pub mod addressforms;
pub mod affine;
pub mod addressvalues;
pub mod assemble;
pub mod allocate;
pub mod arithmetic;
pub mod asm;
pub mod coalesce;
pub mod comparefold;
pub mod constrain;
pub mod copyprop;
pub mod copysink;
pub mod cpu;
pub mod datagroup;
pub mod division;
pub mod farcall;
pub mod farload;
pub mod floatalloc;
pub mod floatregions;
pub mod inline_asm;
pub mod fpu;
pub mod frame;
pub mod jumps;
pub mod lanes;
pub mod layout;
pub mod liveness;
pub mod globals;
pub mod isel;
#[cfg(test)]
mod isel_tests;
pub mod lower;
pub mod lower_floats;
pub mod lower_int64;
pub mod lower_switches;
pub mod machinecse;
pub mod machinedce;
pub mod masm;
pub mod narrow;
pub mod nativeframe;
pub mod omfwrite;
pub mod parcopy;
pub mod peephole;
pub mod phielim;
pub mod pointers;
pub mod prologue;
pub mod regthrash;
pub mod rmw;
pub mod exactaddress;
pub mod executed;
pub mod schedule;
pub mod select;
pub mod spiller;
pub mod spillforward;
pub mod splitkit;
pub mod storecombine;
pub mod target;
pub mod timing;
pub mod twoaddr;
pub mod upperzero;
pub mod verify;

#[cfg(test)]
mod pricing_tests;
