"""Shared helpers for emitting rstest parameterized integration tests."""

from __future__ import annotations


def indent_block(text: str, spaces: int = 4) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" if line else "" for line in text.splitlines())


def render_case_attribute(case_name: str, struct_literal: str) -> str:
    return f"#[case::{case_name}(\n{indent_block(struct_literal, 4)}\n)]"


def render_rstest_function(
    fn_name: str,
    case_type: str,
    cases: list[tuple[str, str]],
    body: str,
    *,
    param_name: str = "case",
) -> str:
    if not cases:
        return ""
    attributes = "\n".join(render_case_attribute(name, literal) for name, literal in cases)
    return f"#[rstest]\n{attributes}\nfn {fn_name}(#[case] {param_name}: {case_type}) {{\n    {body}\n}}"


def render_generated_file(
    generator_name: str,
    struct_block: str,
    rstest_blocks: list[str],
    *,
    const_blocks: list[str] | None = None,
) -> str:
    sections = [
        f"// @generated by tools/{generator_name}; do not edit by hand.",
        "",
        "use rstest::rstest;",
        "",
        struct_block.rstrip(),
    ]
    if const_blocks:
        sections.extend(["", *const_blocks])
    rendered_tests = [block for block in rstest_blocks if block]
    if rendered_tests:
        sections.extend(["", *rendered_tests])
    sections.append("")
    return "\n".join(sections)
