// flags: -O2 -march=i486 -mabi=regparm3
// link: regparm3_matrix_31_callee.c
// Generated by tools/callconv/matrix.py 31 60: random signatures through the register convention, each result checked against a host compiler's.
typedef signed char i8_t;
struct S4 { short a, b; };
struct S8 { long a; short b, c; };
struct S12 { long a, b, c; };
extern void report(long value);
extern short cells[8];

signed char id_i8(signed char x);
unsigned char id_u8(unsigned char x);
short id_i16(short x);
unsigned short id_u16(unsigned short x);
long id_i32(long x);
unsigned long id_u32(unsigned long x);
long long id_i64(long long x);
float id_f32(float x);
double id_f64(double x);
short * id_np(short * x);
short __far * id_fp(short __far * x);
struct S4 id_s4(struct S4 x);
struct S8 id_s8(struct S8 x);
struct S12 id_s12(struct S12 x);
void esc(void *p);
struct S4 mk4(short a, short b) { struct S4 s; s.a = a; s.b = b; return s; }
struct S8 mk8(long a, short b, short c) { struct S8 s; s.a = a; s.b = b; s.c = c; return s; }
struct S12 mk12(long a, long b, long c) { struct S12 s; s.a = a; s.b = b; s.c = c; return s; }
void f0(unsigned char p0, struct S8 p1, long long p2, short p3, short __far * p4, signed char p5, short p6);
signed char f1(struct S4 p0, struct S8 p1, short p2);
unsigned char f2(void);
short * f3(void);
unsigned char f4(double p0, struct S4 p1, float p2);
float f5(unsigned short p0, short * p1, unsigned char p2, unsigned char p3, signed char p4, struct S8 p5);
struct S12 f6(unsigned long p0, unsigned short p1, unsigned short p2, unsigned long p3, long long p4, unsigned long p5);
double f7(unsigned short p0, struct S4 p1, unsigned short p2);
unsigned long f8(void);
void f9(unsigned long p0, short p1);
short f10(struct S12 p0, struct S8 p1);
unsigned long f11(void);
signed char f12(short __far * p0, struct S8 p1, unsigned short p2, unsigned short p3, struct S8 p4, long long p5, struct S4 p6);
long f13(unsigned long p0, short __far * p1, struct S12 p2);
short f14(signed char p0, long p1, unsigned long p2, long p3, unsigned long p4, short * p5, long long p6);
long long f15(unsigned short p0, struct S4 p1, unsigned char p2, struct S8 p3, struct S8 p4);
unsigned short f16(double p0, short * p1);
struct S12 f17(unsigned char p0, short p1, unsigned short p2, signed char p3);
struct S12 f18(struct S4 p0, unsigned char p1, short __far * p2, long long p3, long p4);
struct S12 f19(short __far * p0, struct S12 p1, unsigned short p2, unsigned char p3);
long long f20(struct S8 p0, unsigned long p1, float p2);
unsigned long f21(void);
float f22(long p0);
signed char f23(unsigned short p0);
short f24(short p0, struct S4 p1, struct S12 p2, short p3, float p4);
void f25(short * p0, struct S8 p1, double p2, long p3, struct S12 p4, unsigned long p5, short * p6);
long long f26(void);
struct S8 f27(float p0);
unsigned char f28(struct S12 p0, struct S8 p1, signed char p2, long p3, float p4, struct S8 p5, struct S8 p6);
long long f29(unsigned short p0, signed char p1, unsigned char p2, long long p3, short * p4);
unsigned short f30(short p0, signed char p1, short p2, unsigned char p3, short * p4, struct S12 p5, short * p6);
void f31(struct S8 p0, unsigned short p1, struct S12 p2);
struct S8 f32(struct S4 p0, short p1, double p2, float p3);
float f33(unsigned short p0, double p1, unsigned short p2, struct S4 p3, short * p4, float p5);
unsigned short f34(unsigned long p0, short p1, unsigned long p2, unsigned char p3, double p4, struct S8 p5, unsigned long p6);
short __far * f35(long p0, struct S4 p1, long long p2);
double f36(signed char p0, struct S12 p1);
short * f37(struct S4 p0);
unsigned long f38(short p0, unsigned short p1, long long p2);
struct S12 f39(unsigned short p0, long long p1, struct S4 p2, long p3);
float f40(struct S8 p0, long p1, struct S4 p2);
struct S8 f41(void);
void f42(short * p0, struct S12 p1, long p2, long p3, double p4, unsigned short p5, long long p6);
struct S8 f43(unsigned short p0, long long p1, signed char p2, struct S12 p3, float p4);
unsigned long f44(unsigned short p0, unsigned short p1, unsigned long p2);
long f45(struct S4 p0, unsigned long p1, unsigned char p2, struct S8 p3);
short f46(unsigned short p0);
struct S12 f47(float p0, float p1, short __far * p2, long p3, short __far * p4, short p5, long long p6);
void f48(float p0);
unsigned char f49(struct S8 p0, float p1, struct S12 p2, signed char p3);
void f50(long long p0, long p1, struct S8 p2, long p3);
unsigned short f51(short * p0, long p1, long long p2);
struct S12 f52(unsigned short p0, short * p1, short p2);
struct S8 f53(struct S12 p0, unsigned char p1, short __far * p2, short * p3, struct S4 p4);
short f54(void);
long f55(long p0, short __far * p1, float p2, double p3, struct S12 p4, long p5, long p6);
struct S4 f56(long long p0, short __far * p1, unsigned short p2, double p3, unsigned short p4, struct S8 p5);
unsigned long f57(void);
struct S8 f58(struct S4 p0, unsigned short p1, signed char p2);
struct S8 f59(short __far * p0, unsigned long p1, long p2, unsigned char p3, struct S8 p4, double p5);
void (*p0)(unsigned char p0, struct S8 p1, long long p2, short p3, short __far * p4, signed char p5, short p6) = f0;
signed char (*p1)(struct S4 p0, struct S8 p1, short p2) = f1;
unsigned char (*p2)(void) = f2;
short * (*p3)(void) = f3;
unsigned char (*p4)(double p0, struct S4 p1, float p2) = f4;
float (*p5)(unsigned short p0, short * p1, unsigned char p2, unsigned char p3, signed char p4, struct S8 p5) = f5;
struct S12 (*p6)(unsigned long p0, unsigned short p1, unsigned short p2, unsigned long p3, long long p4, unsigned long p5) = f6;
double (*p7)(unsigned short p0, struct S4 p1, unsigned short p2) = f7;
unsigned long (*p8)(void) = f8;
void (*p9)(unsigned long p0, short p1) = f9;
short (*p10)(struct S12 p0, struct S8 p1) = f10;
unsigned long (*p11)(void) = f11;
signed char (*p12)(short __far * p0, struct S8 p1, unsigned short p2, unsigned short p3, struct S8 p4, long long p5, struct S4 p6) = f12;
long (*p13)(unsigned long p0, short __far * p1, struct S12 p2) = f13;
short (*p14)(signed char p0, long p1, unsigned long p2, long p3, unsigned long p4, short * p5, long long p6) = f14;
long long (*p15)(unsigned short p0, struct S4 p1, unsigned char p2, struct S8 p3, struct S8 p4) = f15;
unsigned short (*p16)(double p0, short * p1) = f16;
struct S12 (*p17)(unsigned char p0, short p1, unsigned short p2, signed char p3) = f17;
struct S12 (*p18)(struct S4 p0, unsigned char p1, short __far * p2, long long p3, long p4) = f18;
struct S12 (*p19)(short __far * p0, struct S12 p1, unsigned short p2, unsigned char p3) = f19;
long long (*p20)(struct S8 p0, unsigned long p1, float p2) = f20;
unsigned long (*p21)(void) = f21;
float (*p22)(long p0) = f22;
signed char (*p23)(unsigned short p0) = f23;
short (*p24)(short p0, struct S4 p1, struct S12 p2, short p3, float p4) = f24;
void (*p25)(short * p0, struct S8 p1, double p2, long p3, struct S12 p4, unsigned long p5, short * p6) = f25;
long long (*p26)(void) = f26;
struct S8 (*p27)(float p0) = f27;
unsigned char (*p28)(struct S12 p0, struct S8 p1, signed char p2, long p3, float p4, struct S8 p5, struct S8 p6) = f28;
long long (*p29)(unsigned short p0, signed char p1, unsigned char p2, long long p3, short * p4) = f29;
unsigned short (*p30)(short p0, signed char p1, short p2, unsigned char p3, short * p4, struct S12 p5, short * p6) = f30;
void (*p31)(struct S8 p0, unsigned short p1, struct S12 p2) = f31;
struct S8 (*p32)(struct S4 p0, short p1, double p2, float p3) = f32;
float (*p33)(unsigned short p0, double p1, unsigned short p2, struct S4 p3, short * p4, float p5) = f33;
unsigned short (*p34)(unsigned long p0, short p1, unsigned long p2, unsigned char p3, double p4, struct S8 p5, unsigned long p6) = f34;
short __far * (*p35)(long p0, struct S4 p1, long long p2) = f35;
double (*p36)(signed char p0, struct S12 p1) = f36;
short * (*p37)(struct S4 p0) = f37;
unsigned long (*p38)(short p0, unsigned short p1, long long p2) = f38;
struct S12 (*p39)(unsigned short p0, long long p1, struct S4 p2, long p3) = f39;
float (*p40)(struct S8 p0, long p1, struct S4 p2) = f40;
struct S8 (*p41)(void) = f41;
void (*p42)(short * p0, struct S12 p1, long p2, long p3, double p4, unsigned short p5, long long p6) = f42;
struct S8 (*p43)(unsigned short p0, long long p1, signed char p2, struct S12 p3, float p4) = f43;
unsigned long (*p44)(unsigned short p0, unsigned short p1, unsigned long p2) = f44;
long (*p45)(struct S4 p0, unsigned long p1, unsigned char p2, struct S8 p3) = f45;
short (*p46)(unsigned short p0) = f46;
struct S12 (*p47)(float p0, float p1, short __far * p2, long p3, short __far * p4, short p5, long long p6) = f47;
void (*p48)(float p0) = f48;
unsigned char (*p49)(struct S8 p0, float p1, struct S12 p2, signed char p3) = f49;
void (*p50)(long long p0, long p1, struct S8 p2, long p3) = f50;
unsigned short (*p51)(short * p0, long p1, long long p2) = f51;
struct S12 (*p52)(unsigned short p0, short * p1, short p2) = f52;
struct S8 (*p53)(struct S12 p0, unsigned char p1, short __far * p2, short * p3, struct S4 p4) = f53;
short (*p54)(void) = f54;
long (*p55)(long p0, short __far * p1, float p2, double p3, struct S12 p4, long p5, long p6) = f55;
struct S4 (*p56)(long long p0, short __far * p1, unsigned short p2, double p3, unsigned short p4, struct S8 p5) = f56;
unsigned long (*p57)(void) = f57;
struct S8 (*p58)(struct S4 p0, unsigned short p1, signed char p2) = f58;
struct S8 (*p59)(short __far * p0, unsigned long p1, long p2, unsigned char p3, struct S8 p4, double p5) = f59;
int main(void) {
    f0(id_u8((unsigned char)103), mk8(10000L, 10, 12), (long long)-22999949LL * 1000LL, (short)-1800, (short __far *)&cells[2], (signed char)-12, (short)4500); report(cells[0]);
    (*p0)(id_u8((unsigned char)103), mk8(10000L, 10, 12), (long long)-22999949LL * 1000LL, (short)-1800, (short __far *)&cells[2], (signed char)-12, (short)4500); report(cells[0]);
    report((long)(f1(id_s4(mk4(10, 11)), mk8(17000L, 17, 19), (short)-1800)));
    report((long)((*p1)(id_s4(mk4(10, 11)), mk8(17000L, 17, 19), (short)-1800)));
    report((long)(f2()));
    report((long)((*p2)()));
    report((long)*f3());
    report((long)*(*p3)());
    report((long)(f4(93.25, id_s4(mk4(38, 39)), 45.5f)));
    report((long)((*p4)(93.25, id_s4(mk4(38, 39)), 45.5f)));
    report((long)(f5(id_u16((unsigned short)22800), &cells[5], (unsigned char)152, (unsigned char)159, id_i8((signed char)16), mk8(73000L, 73, 75))));
    report((long)((*p5)(id_u16((unsigned short)22800), &cells[5], (unsigned char)152, (unsigned char)159, id_i8((signed char)16), mk8(73000L, 73, 75))));
    { struct S12 r = f6(5499595UL, (unsigned short)31200, (unsigned short)35400, 7599406UL, (long long)33000219LL * 1000LL, 8999280UL); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p6)(5499595UL, (unsigned short)31200, (unsigned short)35400, 7599406UL, (long long)33000219LL * 1000LL, 8999280UL); report(r.a ^ r.b ^ r.c); }
    report((long)(f7(id_u16((unsigned short)31200), id_s4(mk4(59, 60)), (unsigned short)39600)));
    report((long)((*p7)(id_u16((unsigned short)31200), id_s4(mk4(59, 60)), (unsigned short)39600)));
    report((long)(f8()));
    report((long)((*p8)()));
    f9(7599406UL, (short)12900); report(cells[1]);
    (*p9)(7599406UL, (short)12900); report(cells[1]);
    report((long)(f10(id_s12(mk12(730L, 78L, 511L)), mk8(80000L, 80, 82))));
    report((long)((*p10)(id_s12(mk12(730L, 78L, 511L)), mk8(80000L, 80, 82))));
    report((long)(f11()));
    report((long)((*p11)()));
    report((long)(f12(id_fp((short __far *)&cells[2]), mk8(94000L, 94, 96), id_u16((unsigned short)600), (unsigned short)4800, id_s8(mk8(15000L, 15, 17)), (long long)-17999934LL * 1000LL, mk4(29, 30))));
    report((long)((*p12)(id_fp((short __far *)&cells[2]), mk8(94000L, 94, 96), id_u16((unsigned short)600), (unsigned short)4800, id_s8(mk8(15000L, 15, 17)), (long long)-17999934LL * 1000LL, mk4(29, 30))));
    report((long)(f13(id_u32(10399154UL), (short __far *)&cells[4], mk12(80L, 13L, 56L))));
    report((long)((*p13)(id_u32(10399154UL), (short __far *)&cells[4], mk12(80L, 13L, 56L))));
    report((long)(f14(id_i8((signed char)-49), id_i32(-2439992L), 2499865UL, -1459978L, 3899739UL, id_np(&cells[4]), (long long)3000129LL * 1000LL)));
    report((long)((*p14)(id_i8((signed char)-49), id_i32(-2439992L), 2499865UL, -1459978L, 3899739UL, id_np(&cells[4]), (long long)3000129LL * 1000LL)));
    { long long r = f15(id_u16((unsigned short)4800), mk4(15, 16), (unsigned char)122, mk8(29000L, 29, 31), mk8(36000L, 36, 38)); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { long long r = (*p15)(id_u16((unsigned short)4800), mk4(15, 16), (unsigned char)122, mk8(29000L, 29, 31), mk8(36000L, 36, 38)); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    report((long)(f16(45.25, &cells[6])));
    report((long)((*p16)(45.25, &cells[6])));
    { struct S12 r = f17((unsigned char)122, (short)-300, id_u16((unsigned short)21600), id_i8((signed char)-7)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p17)((unsigned char)122, (short)-300, id_u16((unsigned short)21600), id_i8((signed char)-7)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = f18(mk4(29, 30), (unsigned char)136, id_fp((short __far *)&cells[6]), (long long)10000150LL * 1000LL, id_i32(990057L)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p18)(mk4(29, 30), (unsigned char)136, id_fp((short __far *)&cells[6]), (long long)10000150LL * 1000LL, id_i32(990057L)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = f19(id_fp((short __far *)&cells[7]), id_s12(mk12(430L, 48L, 301L)), (unsigned short)30000, (unsigned char)157); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p19)(id_fp((short __far *)&cells[7]), id_s12(mk12(430L, 48L, 301L)), (unsigned short)30000, (unsigned char)157); report(r.a ^ r.b ^ r.c); }
    { long long r = f20(id_s8(mk8(43000L, 43, 45)), 5999550UL, id_f32(57.5f)); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { long long r = (*p20)(id_s8(mk8(43000L, 43, 45)), 5999550UL, id_f32(57.5f)); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    report((long)(f21()));
    report((long)((*p21)()));
    report((long)(f22(990057L)));
    report((long)((*p22)(990057L)));
    report((long)(f23((unsigned short)38400)));
    report((long)((*p23)((unsigned short)38400)));
    report((long)(f24(id_i16((short)12300), mk4(78, 79), id_s12(mk12(850L, 90L, 595L)), (short)18600, id_f32(99.5f))));
    report((long)((*p24)(id_i16((short)12300), mk4(78, 79), id_s12(mk12(850L, 90L, 595L)), (short)18600, id_f32(99.5f))));
    f25(id_np(&cells[6]), mk8(85000L, 85, 87), id_f64(276.25), id_i32(3930099L), id_s12(mk12(60L, 11L, 42L)), id_u32(2299883UL), &cells[4]); report(cells[1]);
    (*p25)(id_np(&cells[6]), mk8(85000L, 85, 87), id_f64(276.25), id_i32(3930099L), id_s12(mk12(60L, 11L, 42L)), id_u32(2299883UL), &cells[4]); report(cells[1]);
    { long long r = f26(); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { long long r = (*p26)(); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { struct S8 r = f27(id_f32(92.5f)); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p27)(id_f32(92.5f)); report(r.a + r.b * 5L + r.c); }
    report((long)(f28(id_s12(mk12(990L, 104L, 693L)), mk8(6000L, 6, 8), (signed char)-37, -1599980L, id_f32(27.5f), id_s8(mk8(34000L, 34, 36)), mk8(41000L, 41, 43))));
    report((long)((*p28)(id_s12(mk12(990L, 104L, 693L)), mk8(6000L, 6, 8), (signed char)-37, -1599980L, id_f32(27.5f), id_s8(mk8(34000L, 34, 36)), mk8(41000L, 41, 43))));
    { long long r = f29((unsigned short)3600, (signed char)-37, (unsigned char)120, id_i64((long long)-12999919LL * 1000LL), &cells[2]); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { long long r = (*p29)((unsigned short)3600, (signed char)-37, (unsigned char)120, id_i64((long long)-12999919LL * 1000LL), &cells[2]); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    report((long)(f30((short)-5100, id_i8((signed char)-30), (short)-900, (unsigned char)134, &cells[1], mk12(480L, 53L, 336L), &cells[7])));
    report((long)((*p30)((short)-5100, id_i8((signed char)-30), (short)-900, (unsigned char)134, &cells[1], mk12(480L, 53L, 336L), &cells[7])));
    f31(mk8(20000L, 20, 22), (unsigned short)16200, id_s12(mk12(340L, 39L, 238L))); report(cells[7]);
    (*p31)(mk8(20000L, 20, 22), (unsigned short)16200, id_s12(mk12(340L, 39L, 238L))); report(cells[7]);
    { struct S8 r = f32(id_s4(mk4(27, 28)), id_i16((short)1200), 123.25, 48.5f); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p32)(id_s4(mk4(27, 28)), id_i16((short)1200), 123.25, 48.5f); report(r.a + r.b * 5L + r.c); }
    report((long)(f33((unsigned short)20400, 123.25, (unsigned short)28800, id_s4(mk4(55, 56)), &cells[6], id_f32(69.5f))));
    report((long)((*p33)((unsigned short)20400, 123.25, (unsigned short)28800, id_s4(mk4(55, 56)), &cells[6], id_f32(69.5f))));
    report((long)(f34(id_u32(5099631UL), id_i16((short)5400), 6499505UL, (unsigned char)162, 207.25, id_s8(mk8(76000L, 76, 78)), id_u32(9299253UL))));
    report((long)((*p34)(id_u32(5099631UL), id_i16((short)5400), 6499505UL, (unsigned char)162, 207.25, id_s8(mk8(76000L, 76, 78)), id_u32(9299253UL))));
    report((long)*f35(id_i32(360048L), id_s4(mk4(55, 56)), id_i64((long long)22000186LL * 1000LL)));
    report((long)*(*p35)(id_i32(360048L), id_s4(mk4(55, 56)), id_i64((long long)22000186LL * 1000LL)));
    report((long)(f36((signed char)5, mk12(620L, 67L, 434L))));
    report((long)((*p36)((signed char)5, mk12(620L, 67L, 434L))));
    report((long)*f37(id_s4(mk4(62, 63))));
    report((long)*(*p37)(id_s4(mk4(62, 63))));
    report((long)(f38((short)11700, (unsigned short)45600, id_i64((long long)43000249LL * 1000LL))));
    report((long)((*p38)((short)11700, (unsigned short)45600, id_i64((long long)43000249LL * 1000LL))));
    { struct S12 r = f39(id_u16((unsigned short)45600), (long long)43000249LL * 1000LL, id_s4(mk4(90, 91)), 3790097L); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p39)(id_u16((unsigned short)45600), (long long)43000249LL * 1000LL, id_s4(mk4(90, 91)), 3790097L); report(r.a ^ r.b ^ r.c); }
    report((long)(f40(id_s8(mk8(83000L, 83, 85)), 3300090L, mk4(97, 98))));
    report((long)((*p40)(id_s8(mk8(83000L, 83, 85)), 3300090L, mk4(97, 98))));
    { struct S8 r = f41(); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p41)(); report(r.a + r.b * 5L + r.c); }
    f42(id_np(&cells[1]), id_s12(mk12(40L, 9L, 28L)), -2229989L, -1739982L, id_f64(75.25), id_u16((unsigned short)19200), id_i64((long long)-999883LL * 1000LL)); report(cells[2]);
    (*p42)(id_np(&cells[1]), id_s12(mk12(40L, 9L, 28L)), -2229989L, -1739982L, id_f64(75.25), id_u16((unsigned short)19200), id_i64((long long)-999883LL * 1000LL)); report(cells[2]);
    { struct S8 r = f43((unsigned short)2400, (long long)-28999967LL * 1000LL, id_i8((signed char)-32), mk12(250L, 30L, 175L), id_f32(32.5f)); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p43)((unsigned short)2400, (long long)-28999967LL * 1000LL, id_i8((signed char)-32), mk12(250L, 30L, 175L), id_f32(32.5f)); report(r.a + r.b * 5L + r.c); }
    report((long)(f44(id_u16((unsigned short)6600), (unsigned short)10800, 3499775UL)));
    report((long)((*p44)(id_u16((unsigned short)6600), (unsigned short)10800, 3499775UL)));
    report((long)(f45(mk4(18, 19), 3499775UL, (unsigned char)132, mk8(39000L, 39, 41))));
    report((long)((*p45)(mk4(18, 19), 3499775UL, (unsigned char)132, mk8(39000L, 39, 41))));
    report((long)(f46(id_u16((unsigned short)15000))));
    report((long)((*p46)(id_u16((unsigned short)15000))));
    { struct S12 r = f47(id_f32(32.5f), id_f32(39.5f), (short __far *)&cells[1], id_i32(710053L), (short __far *)&cells[7], id_i16((short)11100), (long long)34000222LL * 1000LL); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p47)(id_f32(32.5f), id_f32(39.5f), (short __far *)&cells[1], id_i32(710053L), (short __far *)&cells[7], id_i16((short)11100), (long long)34000222LL * 1000LL); report(r.a ^ r.b ^ r.c); }
    f48(39.5f); report(cells[0]);
    (*p48)(39.5f); report(cells[0]);
    report((long)(f49(mk8(46000L, 46, 48), 53.5f, mk12(600L, 65L, 420L), (signed char)17)));
    report((long)((*p49)(mk8(46000L, 46, 48), 53.5f, mk12(600L, 65L, 420L), (signed char)17)));
    f50(id_i64((long long)13000159LL * 1000LL), 1200060L, mk8(67000L, 67, 69), id_i32(2180074L)); report(cells[2]);
    (*p50)(id_i64((long long)13000159LL * 1000LL), 1200060L, mk8(67000L, 67, 69), id_i32(2180074L)); report(cells[2]);
    report((long)(f51(&cells[4], id_i32(1690067L), (long long)34000222LL * 1000LL)));
    report((long)((*p51)(&cells[4], id_i32(1690067L), (long long)34000222LL * 1000LL)));
    { struct S12 r = f52(id_u16((unsigned short)40200), &cells[2], (short)15300); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p52)(id_u16((unsigned short)40200), &cells[2], (short)15300); report(r.a ^ r.b ^ r.c); }
    { struct S8 r = f53(id_s12(mk12(740L, 79L, 518L)), (unsigned char)181, id_fp((short __far *)&cells[3]), id_np(&cells[7]), mk4(2, 3)); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p53)(id_s12(mk12(740L, 79L, 518L)), (unsigned char)181, id_fp((short __far *)&cells[3]), id_np(&cells[7]), mk4(2, 3)); report(r.a + r.b * 5L + r.c); }
    report((long)(f54()));
    report((long)((*p54)()));
    report((long)(f55(id_i32(3160088L), (short __far *)&cells[2], 2.5f, 27.25, mk12(160L, 21L, 112L), -1389977L, -899970L)));
    report((long)((*p55)(id_i32(3160088L), (short __far *)&cells[2], 2.5f, 27.25, mk12(160L, 21L, 112L), -1389977L, -899970L)));
    { struct S4 r = f56(id_i64((long long)55000285LL * 1000LL), (short __far *)&cells[5], (unsigned short)5400, id_f64(48.25), id_u16((unsigned short)13800), id_s8(mk8(30000L, 30, 32))); report(r.a * 3L + r.b); }
    { struct S4 r = (*p56)(id_i64((long long)55000285LL * 1000LL), (short __far *)&cells[5], (unsigned short)5400, id_f64(48.25), id_u16((unsigned short)13800), id_s8(mk8(30000L, 30, 32))); report(r.a * 3L + r.b); }
    report((long)(f57()));
    report((long)((*p57)()));
    { struct S8 r = f58(id_s4(mk4(9, 10)), (unsigned short)9600, (signed char)-27); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p58)(id_s4(mk4(9, 10)), (unsigned short)9600, (signed char)-27); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = f59((short __far *)&cells[3], id_u32(3299793UL), id_i32(-899970L), (unsigned char)137, mk8(44000L, 44, 46), id_f64(153.25)); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p59)((short __far *)&cells[3], id_u32(3299793UL), id_i32(-899970L), (unsigned char)137, mk8(44000L, 44, 46), id_f64(153.25)); report(r.a + r.b * 5L + r.c); }
    return 0;
}
