// flags: -O2 -march=i486 -mabi=regparm3
// link: regparm3_matrix_22_callee.c
// Generated by tools/callconv/matrix.py 22 60: random signatures through the register convention, each result checked against a host compiler's.
typedef signed char i8_t;
struct S4 { short a, b; };
struct S8 { long a; short b, c; };
struct S12 { long a, b, c; };
extern void report(long value);
extern short cells[8];

signed char id_i8(signed char x);
unsigned char id_u8(unsigned char x);
short id_i16(short x);
unsigned short id_u16(unsigned short x);
long id_i32(long x);
unsigned long id_u32(unsigned long x);
long long id_i64(long long x);
float id_f32(float x);
double id_f64(double x);
short * id_np(short * x);
short __far * id_fp(short __far * x);
struct S4 id_s4(struct S4 x);
struct S8 id_s8(struct S8 x);
struct S12 id_s12(struct S12 x);
void esc(void *p);
struct S4 mk4(short a, short b) { struct S4 s; s.a = a; s.b = b; return s; }
struct S8 mk8(long a, short b, short c) { struct S8 s; s.a = a; s.b = b; s.c = c; return s; }
struct S12 mk12(long a, long b, long c) { struct S12 s; s.a = a; s.b = b; s.c = c; return s; }
struct S12 f0(unsigned short p0, signed char p1);
double f1(short p0, struct S4 p1, unsigned char p2, struct S4 p3, short __far * p4, unsigned long p5, struct S8 p6);
struct S12 f2(unsigned short p0);
unsigned short f3(void);
long f4(double p0, short __far * p1);
short __far * f5(struct S4 p0, signed char p1, short * p2, signed char p3, short * p4, long p5);
unsigned short f6(unsigned short p0, short p1, struct S12 p2, unsigned char p3, short * p4, double p5);
short __far * f7(void);
short __far * f8(short * p0, unsigned long p1, long p2, short p3, long long p4);
unsigned short f9(long p0, struct S12 p1);
unsigned short f10(long long p0, signed char p1);
long f11(void);
unsigned long f12(double p0, long p1, double p2, long long p3);
unsigned long f13(long p0, short * p1);
long f14(short * p0, signed char p1, long p2, short * p3, short * p4, double p5);
float f15(struct S8 p0, short __far * p1, double p2, long long p3, unsigned char p4, unsigned char p5);
long long f16(unsigned char p0, long long p1, struct S8 p2, long long p3, signed char p4);
struct S12 f17(double p0, unsigned short p1, long long p2);
void f18(float p0);
struct S12 f19(short p0, signed char p1, double p2);
unsigned long f20(short p0, unsigned long p1, unsigned long p2, short __far * p3, unsigned short p4);
long long f21(void);
signed char f22(struct S8 p0, struct S8 p1);
short * f23(short __far * p0, struct S4 p1, unsigned char p2);
void f24(long long p0, unsigned char p1, struct S12 p2);
unsigned char f25(signed char p0, struct S12 p1, unsigned char p2, float p3, struct S4 p4, double p5, short p6);
double f26(short __far * p0, struct S4 p1, struct S12 p2, float p3);
long long f27(short __far * p0);
short __far * f28(struct S8 p0, unsigned char p1, struct S12 p2, struct S8 p3, short * p4);
unsigned short f29(signed char p0);
unsigned char f30(short __far * p0, unsigned char p1, unsigned long p2, unsigned char p3, short p4);
short * f31(struct S4 p0, long p1, short p2, signed char p3, unsigned char p4, unsigned short p5);
long f32(unsigned short p0);
float f33(float p0, struct S12 p1, unsigned char p2, short p3);
void f34(struct S8 p0, unsigned char p1, short * p2, float p3);
double f35(long long p0, unsigned long p1, unsigned char p2);
short __far * f36(signed char p0, unsigned short p1);
unsigned long f37(void);
short f38(struct S8 p0, float p1, short __far * p2);
unsigned long f39(void);
struct S4 f40(float p0, long p1, unsigned short p2, unsigned short p3, unsigned char p4, long p5);
struct S12 f41(short __far * p0);
double f42(short p0, short __far * p1);
long f43(void);
void f44(short p0, short * p1, long p2, signed char p3, struct S12 p4, float p5, struct S4 p6);
void f45(struct S8 p0, struct S8 p1, signed char p2, unsigned short p3);
short * f46(struct S12 p0, short __far * p1, unsigned short p2, float p3, double p4, long long p5, short p6);
long f47(long p0, struct S12 p1, struct S12 p2, struct S4 p3, signed char p4);
short __far * f48(short * p0, short __far * p1, unsigned char p2, short p3, struct S12 p4, struct S8 p5);
struct S12 f49(long p0, struct S12 p1, struct S12 p2, double p3, long p4);
short f50(long p0, double p1, short p2, unsigned long p3);
struct S8 f51(struct S4 p0, float p1, struct S12 p2, short p3, double p4, unsigned short p5, float p6);
unsigned long f52(struct S12 p0, struct S8 p1, unsigned char p2, long long p3, short __far * p4);
short * f53(struct S4 p0, short p1, unsigned char p2);
void f54(unsigned long p0, unsigned short p1, signed char p2, double p3, double p4, struct S12 p5);
unsigned char f55(double p0, unsigned long p1, struct S12 p2);
double f56(void);
float f57(struct S8 p0, struct S8 p1, signed char p2, unsigned char p3, double p4);
short * f58(void);
struct S4 f59(unsigned char p0);
struct S12 (*p0)(unsigned short p0, signed char p1) = f0;
double (*p1)(short p0, struct S4 p1, unsigned char p2, struct S4 p3, short __far * p4, unsigned long p5, struct S8 p6) = f1;
struct S12 (*p2)(unsigned short p0) = f2;
unsigned short (*p3)(void) = f3;
long (*p4)(double p0, short __far * p1) = f4;
short __far * (*p5)(struct S4 p0, signed char p1, short * p2, signed char p3, short * p4, long p5) = f5;
unsigned short (*p6)(unsigned short p0, short p1, struct S12 p2, unsigned char p3, short * p4, double p5) = f6;
short __far * (*p7)(void) = f7;
short __far * (*p8)(short * p0, unsigned long p1, long p2, short p3, long long p4) = f8;
unsigned short (*p9)(long p0, struct S12 p1) = f9;
unsigned short (*p10)(long long p0, signed char p1) = f10;
long (*p11)(void) = f11;
unsigned long (*p12)(double p0, long p1, double p2, long long p3) = f12;
unsigned long (*p13)(long p0, short * p1) = f13;
long (*p14)(short * p0, signed char p1, long p2, short * p3, short * p4, double p5) = f14;
float (*p15)(struct S8 p0, short __far * p1, double p2, long long p3, unsigned char p4, unsigned char p5) = f15;
long long (*p16)(unsigned char p0, long long p1, struct S8 p2, long long p3, signed char p4) = f16;
struct S12 (*p17)(double p0, unsigned short p1, long long p2) = f17;
void (*p18)(float p0) = f18;
struct S12 (*p19)(short p0, signed char p1, double p2) = f19;
unsigned long (*p20)(short p0, unsigned long p1, unsigned long p2, short __far * p3, unsigned short p4) = f20;
long long (*p21)(void) = f21;
signed char (*p22)(struct S8 p0, struct S8 p1) = f22;
short * (*p23)(short __far * p0, struct S4 p1, unsigned char p2) = f23;
void (*p24)(long long p0, unsigned char p1, struct S12 p2) = f24;
unsigned char (*p25)(signed char p0, struct S12 p1, unsigned char p2, float p3, struct S4 p4, double p5, short p6) = f25;
double (*p26)(short __far * p0, struct S4 p1, struct S12 p2, float p3) = f26;
long long (*p27)(short __far * p0) = f27;
short __far * (*p28)(struct S8 p0, unsigned char p1, struct S12 p2, struct S8 p3, short * p4) = f28;
unsigned short (*p29)(signed char p0) = f29;
unsigned char (*p30)(short __far * p0, unsigned char p1, unsigned long p2, unsigned char p3, short p4) = f30;
short * (*p31)(struct S4 p0, long p1, short p2, signed char p3, unsigned char p4, unsigned short p5) = f31;
long (*p32)(unsigned short p0) = f32;
float (*p33)(float p0, struct S12 p1, unsigned char p2, short p3) = f33;
void (*p34)(struct S8 p0, unsigned char p1, short * p2, float p3) = f34;
double (*p35)(long long p0, unsigned long p1, unsigned char p2) = f35;
short __far * (*p36)(signed char p0, unsigned short p1) = f36;
unsigned long (*p37)(void) = f37;
short (*p38)(struct S8 p0, float p1, short __far * p2) = f38;
unsigned long (*p39)(void) = f39;
struct S4 (*p40)(float p0, long p1, unsigned short p2, unsigned short p3, unsigned char p4, long p5) = f40;
struct S12 (*p41)(short __far * p0) = f41;
double (*p42)(short p0, short __far * p1) = f42;
long (*p43)(void) = f43;
void (*p44)(short p0, short * p1, long p2, signed char p3, struct S12 p4, float p5, struct S4 p6) = f44;
void (*p45)(struct S8 p0, struct S8 p1, signed char p2, unsigned short p3) = f45;
short * (*p46)(struct S12 p0, short __far * p1, unsigned short p2, float p3, double p4, long long p5, short p6) = f46;
long (*p47)(long p0, struct S12 p1, struct S12 p2, struct S4 p3, signed char p4) = f47;
short __far * (*p48)(short * p0, short __far * p1, unsigned char p2, short p3, struct S12 p4, struct S8 p5) = f48;
struct S12 (*p49)(long p0, struct S12 p1, struct S12 p2, double p3, long p4) = f49;
short (*p50)(long p0, double p1, short p2, unsigned long p3) = f50;
struct S8 (*p51)(struct S4 p0, float p1, struct S12 p2, short p3, double p4, unsigned short p5, float p6) = f51;
unsigned long (*p52)(struct S12 p0, struct S8 p1, unsigned char p2, long long p3, short __far * p4) = f52;
short * (*p53)(struct S4 p0, short p1, unsigned char p2) = f53;
void (*p54)(unsigned long p0, unsigned short p1, signed char p2, double p3, double p4, struct S12 p5) = f54;
unsigned char (*p55)(double p0, unsigned long p1, struct S12 p2) = f55;
double (*p56)(void) = f56;
float (*p57)(struct S8 p0, struct S8 p1, signed char p2, unsigned char p3, double p4) = f57;
short * (*p58)(void) = f58;
struct S4 (*p59)(unsigned char p0) = f59;
int main(void) {
    { struct S12 r = f0(id_u16((unsigned short)1800), (signed char)-40); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p0)(id_u16((unsigned short)1800), (signed char)-40); report(r.a ^ r.b ^ r.c); }
    report((long)(f1((short)-6000, mk4(17, 18), (unsigned char)124, id_s4(mk4(31, 32)), (short __far *)&cells[1], id_u32(5499595UL), mk8(52000L, 52, 54))));
    report((long)((*p1)((short)-6000, mk4(17, 18), (unsigned char)124, id_s4(mk4(31, 32)), (short __far *)&cells[1], id_u32(5499595UL), mk8(52000L, 52, 54))));
    { struct S12 r = f2(id_u16((unsigned short)10200)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p2)(id_u16((unsigned short)10200)); report(r.a ^ r.b ^ r.c); }
    report((long)(f3()));
    report((long)((*p3)()));
    report((long)(f4(id_f64(93.25), id_fp((short __far *)&cells[1]))));
    report((long)((*p4)(id_f64(93.25), id_fp((short __far *)&cells[1]))));
    report((long)*f5(mk4(38, 39), id_i8((signed char)-5), &cells[4], (signed char)9, &cells[2], id_i32(2110073L)));
    report((long)*(*p5)(mk4(38, 39), id_i8((signed char)-5), &cells[4], (signed char)9, &cells[2], id_i32(2110073L)));
    report((long)(f6((unsigned short)27000, id_i16((short)6600), id_s12(mk12(590L, 64L, 413L)), id_u8((unsigned char)166), &cells[1], 240.25)));
    report((long)((*p6)((unsigned short)27000, id_i16((short)6600), id_s12(mk12(590L, 64L, 413L)), id_u8((unsigned char)166), &cells[1], 240.25)));
    report((long)*f7());
    report((long)*(*p7)());
    report((long)*f8(id_np(&cells[3]), 7599406UL, id_i32(2110073L), (short)15000, (long long)47000261LL * 1000LL));
    report((long)*(*p8)(id_np(&cells[3]), 7599406UL, id_i32(2110073L), (short)15000, (long long)47000261LL * 1000LL));
    report((long)(f9(1620066L, id_s12(mk12(730L, 78L, 511L)))));
    report((long)((*p9)(1620066L, id_s12(mk12(730L, 78L, 511L)))));
    report((long)(f10((long long)33000219LL * 1000LL, (signed char)30)));
    report((long)((*p10)((long long)33000219LL * 1000LL, (signed char)30)));
    report((long)(f11()));
    report((long)((*p11)()));
    report((long)(f12(261.25, 3580094L, 3.25, (long long)-31999976LL * 1000LL)));
    report((long)((*p12)(261.25, 3580094L, 3.25, (long long)-31999976LL * 1000LL)));
    report((long)(f13(id_i32(3580094L), id_np(&cells[1]))));
    report((long)((*p13)(id_i32(3580094L), id_np(&cells[1]))));
    report((long)(f14(&cells[1], id_i8((signed char)-42), id_i32(-1949985L), &cells[6], &cells[5], id_f64(108.25))));
    report((long)((*p14)(&cells[1], id_i8((signed char)-42), id_i32(-1949985L), &cells[6], &cells[5], id_f64(108.25))));
    report((long)(f15(mk8(8000L, 8, 10), (short __far *)&cells[2], 66.25, id_i64((long long)-10999913LL * 1000LL), id_u8((unsigned char)136), (unsigned char)143)));
    report((long)((*p15)(mk8(8000L, 8, 10), (short __far *)&cells[2], 66.25, id_i64((long long)-10999913LL * 1000LL), id_u8((unsigned char)136), (unsigned char)143)));
    { long long r = f16((unsigned char)115, (long long)-17999934LL * 1000LL, mk8(29000L, 29, 31), id_i64((long long)-3999892LL * 1000LL), (signed char)-7); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { long long r = (*p16)((unsigned char)115, (long long)-17999934LL * 1000LL, mk8(29000L, 29, 31), id_i64((long long)-3999892LL * 1000LL), (signed char)-7); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { struct S12 r = f17(id_f64(66.25), id_u16((unsigned short)17400), (long long)-3999892LL * 1000LL); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p17)(id_f64(66.25), id_u16((unsigned short)17400), (long long)-3999892LL * 1000LL); report(r.a ^ r.b ^ r.c); }
    f18(29.5f); report(cells[2]);
    (*p18)(29.5f); report(cells[2]);
    { struct S12 r = f19((short)1800, (signed char)-7, id_f64(150.25)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p19)((short)1800, (signed char)-7, id_f64(150.25)); report(r.a ^ r.b ^ r.c); }
    report((long)(f20((short)3900, 5999550UL, 6699487UL, (short __far *)&cells[3], (unsigned short)42600)));
    report((long)((*p20)((short)3900, 5999550UL, 6699487UL, (short __far *)&cells[3], (unsigned short)42600)));
    { long long r = f21(); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { long long r = (*p21)(); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    report((long)(f22(id_s8(mk8(57000L, 57, 59)), mk8(64000L, 64, 66))));
    report((long)((*p22)(id_s8(mk8(57000L, 57, 59)), mk8(64000L, 64, 66))));
    report((long)*f23(id_fp((short __far *)&cells[3]), id_s4(mk4(71, 72)), id_u8((unsigned char)178)));
    report((long)*(*p23)(id_fp((short __far *)&cells[3]), id_s4(mk4(71, 72)), id_u8((unsigned char)178)));
    f24(id_i64((long long)31000213LL * 1000LL), (unsigned char)178, mk12(850L, 90L, 595L)); report(cells[0]);
    (*p24)(id_i64((long long)31000213LL * 1000LL), (unsigned char)178, mk12(850L, 90L, 595L)); report(cells[0]);
    report((long)(f25((signed char)28, mk12(850L, 90L, 595L), id_u8((unsigned char)192), id_f32(99.5f), id_s4(mk4(6, 7)), 39.25, (short)-3000)));
    report((long)((*p25)((signed char)28, mk12(850L, 90L, 595L), id_u8((unsigned char)192), id_f32(99.5f), id_s4(mk4(6, 7)), 39.25, (short)-3000)));
    report((long)(f26(id_fp((short __far *)&cells[0]), mk4(92, 93), mk12(990L, 104L, 693L), 6.5f)));
    report((long)((*p26)(id_fp((short __far *)&cells[0]), mk4(92, 93), mk12(990L, 104L, 693L), 6.5f)));
    { long long r = f27((short __far *)&cells[7]); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { long long r = (*p27)((short __far *)&cells[7]); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    report((long)*f28(mk8(99000L, 99, 101), (unsigned char)106, mk12(130L, 18L, 91L), id_s8(mk8(20000L, 20, 22)), id_np(&cells[3])));
    report((long)*(*p28)(mk8(99000L, 99, 101), (unsigned char)106, mk12(130L, 18L, 91L), id_s8(mk8(20000L, 20, 22)), id_np(&cells[3])));
    report((long)(f29(id_i8((signed char)-44))));
    report((long)((*p29)(id_i8((signed char)-44))));
    report((long)(f30(id_fp((short __far *)&cells[0]), (unsigned char)120, 3699757UL, (unsigned char)134, (short)3300)));
    report((long)((*p30)(id_fp((short __far *)&cells[0]), (unsigned char)120, 3699757UL, (unsigned char)134, (short)3300)));
    report((long)*f31(id_s4(mk4(20, 21)), -1109973L, id_i16((short)1200), id_i8((signed char)-9), (unsigned char)148, id_u16((unsigned short)33000)));
    report((long)*(*p31)(id_s4(mk4(20, 21)), -1109973L, id_i16((short)1200), id_i8((signed char)-9), (unsigned char)148, id_u16((unsigned short)33000)));
    report((long)(f32(id_u16((unsigned short)16200))));
    report((long)((*p32)(id_u16((unsigned short)16200))));
    report((long)(f33(34.5f, id_s12(mk12(410L, 46L, 287L)), (unsigned char)148, (short)7500)));
    report((long)((*p33)(34.5f, id_s12(mk12(410L, 46L, 287L)), (unsigned char)148, (short)7500)));
    f34(id_s8(mk8(41000L, 41, 43)), id_u8((unsigned char)148), &cells[7], 62.5f); report(cells[2]);
    (*p34)(id_s8(mk8(41000L, 41, 43)), id_u8((unsigned char)148), &cells[7], 62.5f); report(cells[2]);
    report((long)(f35(id_i64((long long)8000144LL * 1000LL), 6499505UL, (unsigned char)162)));
    report((long)((*p35)(id_i64((long long)8000144LL * 1000LL), 6499505UL, (unsigned char)162)));
    report((long)*f36(id_i8((signed char)5), id_u16((unsigned short)37200)));
    report((long)*(*p36)(id_i8((signed char)5), id_u16((unsigned short)37200)));
    report((long)(f37()));
    report((long)((*p37)()));
    report((long)(f38(mk8(69000L, 69, 71), id_f32(76.5f), (short __far *)&cells[6])));
    report((long)((*p38)(mk8(69000L, 69, 71), id_f32(76.5f), (short __far *)&cells[6])));
    report((long)(f39()));
    report((long)((*p39)()));
    { struct S4 r = f40(id_f32(83.5f), 3300090L, (unsigned short)58200, id_u16((unsigned short)2400), (unsigned char)111, -1739982L); report(r.a * 3L + r.b); }
    { struct S4 r = (*p40)(id_f32(83.5f), 3300090L, (unsigned short)58200, id_u16((unsigned short)2400), (unsigned char)111, -1739982L); report(r.a * 3L + r.b); }
    { struct S12 r = f41((short __far *)&cells[5]); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p41)((short __far *)&cells[5]); report(r.a ^ r.b ^ r.c); }
    report((long)(f42((short)20100, id_fp((short __far *)&cells[7]))));
    report((long)((*p42)((short)20100, id_fp((short __far *)&cells[7]))));
    report((long)(f43()));
    report((long)((*p43)()));
    f44((short)-5700, id_np(&cells[2]), -1249975L, id_i8((signed char)-18), id_s12(mk12(390L, 44L, 273L)), id_f32(46.5f), id_s4(mk4(53, 54))); report(cells[4]);
    (*p44)((short)-5700, id_np(&cells[2]), -1249975L, id_i8((signed char)-18), id_s12(mk12(390L, 44L, 273L)), id_f32(46.5f), id_s4(mk4(53, 54))); report(cells[4]);
    f45(mk8(18000L, 18, 20), id_s8(mk8(25000L, 25, 27)), (signed char)-18, id_u16((unsigned short)23400)); report(cells[5]);
    (*p45)(mk8(18000L, 18, 20), id_s8(mk8(25000L, 25, 27)), (signed char)-18, id_u16((unsigned short)23400)); report(cells[5]);
    report((long)*f46(id_s12(mk12(250L, 30L, 175L)), id_fp((short __far *)&cells[3]), id_u16((unsigned short)23400), 46.5f, 159.25, (long long)20000180LL * 1000LL, (short)11100));
    report((long)*(*p46)(id_s12(mk12(250L, 30L, 175L)), id_fp((short __far *)&cells[3]), id_u16((unsigned short)23400), 46.5f, 159.25, (long long)20000180LL * 1000LL, (short)11100));
    report((long)(f47(-759968L, mk12(390L, 44L, 273L), mk12(460L, 51L, 322L), mk4(53, 54), (signed char)10)));
    report((long)((*p47)(-759968L, mk12(390L, 44L, 273L), mk12(460L, 51L, 322L), mk4(53, 54), (signed char)10)));
    report((long)*f48(&cells[7], id_fp((short __far *)&cells[1]), id_u8((unsigned char)153), id_i16((short)9000), id_s12(mk12(670L, 72L, 469L)), mk8(74000L, 74, 76)));
    report((long)*(*p48)(&cells[7], id_fp((short __far *)&cells[1]), id_u8((unsigned char)153), id_i16((short)9000), id_s12(mk12(670L, 72L, 469L)), mk8(74000L, 74, 76)));
    { struct S12 r = f49(220046L, mk12(530L, 58L, 371L), id_s12(mk12(600L, 65L, 420L)), 201.25, 2180074L); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p49)(220046L, mk12(530L, 58L, 371L), id_s12(mk12(600L, 65L, 420L)), 201.25, 2180074L); report(r.a ^ r.b ^ r.c); }
    report((long)(f50(710053L, 180.25, id_i16((short)11100), 8399334UL)));
    report((long)((*p50)(710053L, 180.25, id_i16((short)11100), 8399334UL)));
    { struct S8 r = f51(mk4(60, 61), id_f32(67.5f), mk12(740L, 79L, 518L), id_i16((short)15300), 264.25, id_u16((unsigned short)57000), 2.5f); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p51)(mk4(60, 61), id_f32(67.5f), mk12(740L, 79L, 518L), id_i16((short)15300), 264.25, id_u16((unsigned short)57000), 2.5f); report(r.a + r.b * 5L + r.c); }
    report((long)(f52(mk12(670L, 72L, 469L), id_s8(mk8(74000L, 74, 76)), (unsigned char)181, (long long)48000264LL * 1000LL, (short __far *)&cells[2])));
    report((long)((*p52)(mk12(670L, 72L, 469L), id_s8(mk8(74000L, 74, 76)), (unsigned char)181, (long long)48000264LL * 1000LL, (short __far *)&cells[2])));
    report((long)*f53(mk4(74, 75), (short)15300, (unsigned char)188));
    report((long)*(*p53)(mk4(74, 75), (short)15300, (unsigned char)188));
    f54(id_u32(9099271UL), id_u16((unsigned short)52800), id_i8((signed char)45), id_f64(6.25), id_f64(27.25), mk12(160L, 21L, 112L)); report(cells[6]);
    (*p54)(id_u32(9099271UL), id_u16((unsigned short)52800), id_i8((signed char)45), id_f64(6.25), id_f64(27.25), mk12(160L, 21L, 112L)); report(cells[6]);
    report((long)(f55(id_f64(264.25), id_u32(10499145UL), id_s12(mk12(20L, 7L, 14L)))));
    report((long)((*p55)(id_f64(264.25), id_u32(10499145UL), id_s12(mk12(20L, 7L, 14L)))));
    report((long)(f56()));
    report((long)((*p56)()));
    report((long)(f57(id_s8(mk8(2000L, 2, 4)), id_s8(mk8(9000L, 9, 11)), (signed char)-34, (unsigned char)123, 90.25)));
    report((long)((*p57)(id_s8(mk8(2000L, 2, 4)), id_s8(mk8(9000L, 9, 11)), (signed char)-34, (unsigned char)123, 90.25)));
    report((long)*f58());
    report((long)*(*p58)());
    { struct S4 r = f59((unsigned char)116); report(r.a * 3L + r.b); }
    { struct S4 r = (*p59)((unsigned char)116); report(r.a * 3L + r.b); }
    return 0;
}
