// flags: -O2 -march=i486 -mabi=regparm3
// link: regparm3_matrix_4_callee.c
// Generated by tools/callconv/matrix.py 4 60: random signatures through the register convention, each result checked against a host compiler's.
typedef signed char i8_t;
struct S4 { short a, b; };
struct S8 { long a; short b, c; };
struct S12 { long a, b, c; };
extern void report(long value);
extern short cells[8];

signed char id_i8(signed char x);
unsigned char id_u8(unsigned char x);
short id_i16(short x);
unsigned short id_u16(unsigned short x);
long id_i32(long x);
unsigned long id_u32(unsigned long x);
long long id_i64(long long x);
float id_f32(float x);
double id_f64(double x);
short * id_np(short * x);
short __far * id_fp(short __far * x);
struct S4 id_s4(struct S4 x);
struct S8 id_s8(struct S8 x);
struct S12 id_s12(struct S12 x);
void esc(void *p);
struct S4 mk4(short a, short b) { struct S4 s; s.a = a; s.b = b; return s; }
struct S8 mk8(long a, short b, short c) { struct S8 s; s.a = a; s.b = b; s.c = c; return s; }
struct S12 mk12(long a, long b, long c) { struct S12 s; s.a = a; s.b = b; s.c = c; return s; }
short f0(unsigned char p0, struct S4 p1, long long p2, float p3);
unsigned char f1(unsigned char p0);
void f2(double p0, long p1, struct S8 p2, struct S8 p3, signed char p4, unsigned short p5);
float f3(long p0, struct S8 p1, short p2, struct S12 p3, unsigned char p4);
unsigned short f4(signed char p0, struct S12 p1, short __far * p2);
struct S4 f5(struct S8 p0, long p1, unsigned short p2, short p3);
unsigned short f6(short __far * p0, struct S12 p1, struct S4 p2, struct S12 p3);
struct S8 f7(unsigned char p0, struct S12 p1, short * p2, unsigned long p3, short __far * p4);
unsigned long f8(short p0, unsigned short p1, float p2);
unsigned short f9(struct S12 p0);
struct S8 f10(signed char p0, long p1, short * p2, struct S4 p3);
struct S12 f11(struct S12 p0, struct S8 p1, double p2, unsigned short p3);
unsigned long f12(short * p0, long p1, long long p2, float p3, short p4, unsigned short p5);
unsigned short f13(struct S12 p0, struct S8 p1, signed char p2, unsigned char p3);
void f14(short __far * p0, long p1, double p2, double p3, short __far * p4, float p5, struct S4 p6);
long f15(short __far * p0, unsigned short p1);
signed char f16(unsigned short p0, short __far * p1, short __far * p2, float p3, long p4, short p5);
long f17(struct S4 p0, short * p1, unsigned long p2, short __far * p3, double p4, unsigned short p5);
struct S12 f18(unsigned char p0, struct S12 p1, signed char p2, struct S4 p3, unsigned short p4);
unsigned short f19(unsigned char p0, unsigned long p1, short p2);
unsigned short f20(signed char p0, signed char p1, unsigned long p2, struct S4 p3, unsigned char p4, long p5, struct S4 p6);
short * f21(signed char p0, unsigned long p1, long p2, unsigned long p3, short p4);
struct S4 f22(struct S12 p0, struct S12 p1, short * p2, short __far * p3, struct S12 p4, unsigned char p5);
unsigned short f23(float p0, long p1, short p2);
unsigned short f24(short * p0, short p1, unsigned long p2, short * p3, signed char p4, unsigned long p5);
void f25(short p0, unsigned long p1, struct S8 p2, struct S8 p3, unsigned long p4, long p5, short * p6);
signed char f26(unsigned short p0, long long p1, unsigned short p2, unsigned char p3, signed char p4, signed char p5, signed char p6);
short __far * f27(short * p0, short __far * p1);
unsigned char f28(void);
float f29(short * p0, unsigned short p1, unsigned long p2, signed char p3, unsigned char p4, struct S12 p5, double p6);
unsigned short f30(short __far * p0, unsigned short p1, float p2, unsigned short p3, unsigned short p4, float p5);
unsigned long f31(signed char p0, unsigned short p1, long long p2, float p3, unsigned short p4, short __far * p5, long long p6);
struct S8 f32(float p0, unsigned short p1, signed char p2);
void f33(long p0, unsigned short p1, double p2, unsigned short p3);
struct S4 f34(long long p0, struct S12 p1, long p2);
unsigned char f35(signed char p0, unsigned long p1, short * p2, unsigned char p3, short * p4);
unsigned long f36(void);
long long f37(unsigned char p0, long long p1, unsigned short p2, struct S12 p3, short * p4, short p5);
long f38(short __far * p0, float p1, struct S8 p2, short __far * p3);
long f39(double p0, unsigned short p1, short __far * p2, struct S8 p3, short __far * p4, struct S8 p5);
unsigned short f40(long long p0, float p1, unsigned char p2, struct S12 p3, long p4);
short * f41(signed char p0, long long p1, short * p2);
unsigned char f42(short __far * p0, struct S12 p1, signed char p2, struct S12 p3);
unsigned char f43(short * p0, float p1, struct S4 p2, long long p3, long long p4, unsigned short p5, struct S8 p6);
void f44(short p0, signed char p1, short * p2);
struct S12 f45(unsigned char p0, long long p1, struct S8 p2, struct S8 p3);
struct S4 f46(unsigned short p0, double p1, signed char p2, unsigned short p3, short p4, short __far * p5);
double f47(struct S12 p0, double p1, struct S8 p2, struct S8 p3, float p4);
struct S12 f48(signed char p0, unsigned char p1, signed char p2, struct S4 p3, short * p4, unsigned char p5, float p6);
float f49(short * p0, struct S8 p1, short p2, signed char p3);
long f50(struct S8 p0);
struct S12 f51(void);
unsigned short f52(struct S12 p0, unsigned char p1, unsigned char p2, double p3, float p4);
unsigned long f53(struct S8 p0, long p1, long long p2);
short f54(struct S12 p0, long long p1, unsigned char p2, unsigned char p3, unsigned char p4, short * p5, struct S8 p6);
struct S12 f55(double p0, long long p1, long long p2, struct S12 p3, struct S4 p4);
struct S4 f56(unsigned char p0, short __far * p1, unsigned short p2, short __far * p3, long p4, struct S12 p5, float p6);
unsigned long f57(struct S8 p0);
float f58(unsigned long p0, struct S12 p1);
unsigned char f59(struct S4 p0, short p1);
short (*p0)(unsigned char p0, struct S4 p1, long long p2, float p3) = f0;
unsigned char (*p1)(unsigned char p0) = f1;
void (*p2)(double p0, long p1, struct S8 p2, struct S8 p3, signed char p4, unsigned short p5) = f2;
float (*p3)(long p0, struct S8 p1, short p2, struct S12 p3, unsigned char p4) = f3;
unsigned short (*p4)(signed char p0, struct S12 p1, short __far * p2) = f4;
struct S4 (*p5)(struct S8 p0, long p1, unsigned short p2, short p3) = f5;
unsigned short (*p6)(short __far * p0, struct S12 p1, struct S4 p2, struct S12 p3) = f6;
struct S8 (*p7)(unsigned char p0, struct S12 p1, short * p2, unsigned long p3, short __far * p4) = f7;
unsigned long (*p8)(short p0, unsigned short p1, float p2) = f8;
unsigned short (*p9)(struct S12 p0) = f9;
struct S8 (*p10)(signed char p0, long p1, short * p2, struct S4 p3) = f10;
struct S12 (*p11)(struct S12 p0, struct S8 p1, double p2, unsigned short p3) = f11;
unsigned long (*p12)(short * p0, long p1, long long p2, float p3, short p4, unsigned short p5) = f12;
unsigned short (*p13)(struct S12 p0, struct S8 p1, signed char p2, unsigned char p3) = f13;
void (*p14)(short __far * p0, long p1, double p2, double p3, short __far * p4, float p5, struct S4 p6) = f14;
long (*p15)(short __far * p0, unsigned short p1) = f15;
signed char (*p16)(unsigned short p0, short __far * p1, short __far * p2, float p3, long p4, short p5) = f16;
long (*p17)(struct S4 p0, short * p1, unsigned long p2, short __far * p3, double p4, unsigned short p5) = f17;
struct S12 (*p18)(unsigned char p0, struct S12 p1, signed char p2, struct S4 p3, unsigned short p4) = f18;
unsigned short (*p19)(unsigned char p0, unsigned long p1, short p2) = f19;
unsigned short (*p20)(signed char p0, signed char p1, unsigned long p2, struct S4 p3, unsigned char p4, long p5, struct S4 p6) = f20;
short * (*p21)(signed char p0, unsigned long p1, long p2, unsigned long p3, short p4) = f21;
struct S4 (*p22)(struct S12 p0, struct S12 p1, short * p2, short __far * p3, struct S12 p4, unsigned char p5) = f22;
unsigned short (*p23)(float p0, long p1, short p2) = f23;
unsigned short (*p24)(short * p0, short p1, unsigned long p2, short * p3, signed char p4, unsigned long p5) = f24;
void (*p25)(short p0, unsigned long p1, struct S8 p2, struct S8 p3, unsigned long p4, long p5, short * p6) = f25;
signed char (*p26)(unsigned short p0, long long p1, unsigned short p2, unsigned char p3, signed char p4, signed char p5, signed char p6) = f26;
short __far * (*p27)(short * p0, short __far * p1) = f27;
unsigned char (*p28)(void) = f28;
float (*p29)(short * p0, unsigned short p1, unsigned long p2, signed char p3, unsigned char p4, struct S12 p5, double p6) = f29;
unsigned short (*p30)(short __far * p0, unsigned short p1, float p2, unsigned short p3, unsigned short p4, float p5) = f30;
unsigned long (*p31)(signed char p0, unsigned short p1, long long p2, float p3, unsigned short p4, short __far * p5, long long p6) = f31;
struct S8 (*p32)(float p0, unsigned short p1, signed char p2) = f32;
void (*p33)(long p0, unsigned short p1, double p2, unsigned short p3) = f33;
struct S4 (*p34)(long long p0, struct S12 p1, long p2) = f34;
unsigned char (*p35)(signed char p0, unsigned long p1, short * p2, unsigned char p3, short * p4) = f35;
unsigned long (*p36)(void) = f36;
long long (*p37)(unsigned char p0, long long p1, unsigned short p2, struct S12 p3, short * p4, short p5) = f37;
long (*p38)(short __far * p0, float p1, struct S8 p2, short __far * p3) = f38;
long (*p39)(double p0, unsigned short p1, short __far * p2, struct S8 p3, short __far * p4, struct S8 p5) = f39;
unsigned short (*p40)(long long p0, float p1, unsigned char p2, struct S12 p3, long p4) = f40;
short * (*p41)(signed char p0, long long p1, short * p2) = f41;
unsigned char (*p42)(short __far * p0, struct S12 p1, signed char p2, struct S12 p3) = f42;
unsigned char (*p43)(short * p0, float p1, struct S4 p2, long long p3, long long p4, unsigned short p5, struct S8 p6) = f43;
void (*p44)(short p0, signed char p1, short * p2) = f44;
struct S12 (*p45)(unsigned char p0, long long p1, struct S8 p2, struct S8 p3) = f45;
struct S4 (*p46)(unsigned short p0, double p1, signed char p2, unsigned short p3, short p4, short __far * p5) = f46;
double (*p47)(struct S12 p0, double p1, struct S8 p2, struct S8 p3, float p4) = f47;
struct S12 (*p48)(signed char p0, unsigned char p1, signed char p2, struct S4 p3, short * p4, unsigned char p5, float p6) = f48;
float (*p49)(short * p0, struct S8 p1, short p2, signed char p3) = f49;
long (*p50)(struct S8 p0) = f50;
struct S12 (*p51)(void) = f51;
unsigned short (*p52)(struct S12 p0, unsigned char p1, unsigned char p2, double p3, float p4) = f52;
unsigned long (*p53)(struct S8 p0, long p1, long long p2) = f53;
short (*p54)(struct S12 p0, long long p1, unsigned char p2, unsigned char p3, unsigned char p4, short * p5, struct S8 p6) = f54;
struct S12 (*p55)(double p0, long long p1, long long p2, struct S12 p3, struct S4 p4) = f55;
struct S4 (*p56)(unsigned char p0, short __far * p1, unsigned short p2, short __far * p3, long p4, struct S12 p5, float p6) = f56;
unsigned long (*p57)(struct S8 p0) = f57;
float (*p58)(unsigned long p0, struct S12 p1) = f58;
unsigned char (*p59)(struct S4 p0, short p1) = f59;
int main(void) {
    report((long)(f0(id_u8((unsigned char)103), mk4(10, 11), (long long)-22999949LL * 1000LL, 24.5f)));
    report((long)((*p0)(id_u8((unsigned char)103), mk4(10, 11), (long long)-22999949LL * 1000LL, 24.5f)));
    report((long)(f1(id_u8((unsigned char)110))));
    report((long)((*p1)(id_u8((unsigned char)110))));
    f2(51.25, id_i32(-1319976L), id_s8(mk8(31000L, 31, 33)), mk8(38000L, 38, 40), id_i8((signed char)-5), (unsigned short)31200); report(cells[2]);
    (*p2)(51.25, id_i32(-1319976L), id_s8(mk8(31000L, 31, 33)), mk8(38000L, 38, 40), id_i8((signed char)-5), (unsigned short)31200); report(cells[2]);
    report((long)(f3(-1319976L, mk8(31000L, 31, 33), (short)2400, id_s12(mk12(450L, 50L, 315L)), (unsigned char)152)));
    report((long)((*p3)(-1319976L, mk8(31000L, 31, 33), (short)2400, id_s12(mk12(450L, 50L, 315L)), (unsigned char)152)));
    report((long)(f4(id_i8((signed char)-19), mk12(380L, 43L, 266L), (short __far *)&cells[0])));
    report((long)((*p4)(id_i8((signed char)-19), mk12(380L, 43L, 266L), (short __far *)&cells[0])));
    { struct S4 r = f5(mk8(38000L, 38, 40), id_i32(150045L), id_u16((unsigned short)31200), (short)8700); report(r.a * 3L + r.b); }
    { struct S4 r = (*p5)(mk8(38000L, 38, 40), id_i32(150045L), id_u16((unsigned short)31200), (short)8700); report(r.a * 3L + r.b); }
    report((long)(f6(id_fp((short __far *)&cells[0]), id_s12(mk12(520L, 57L, 364L)), mk4(59, 60), mk12(660L, 71L, 462L))));
    report((long)((*p6)(id_fp((short __far *)&cells[0]), id_s12(mk12(520L, 57L, 364L)), mk4(59, 60), mk12(660L, 71L, 462L))));
    { struct S8 r = f7((unsigned char)152, id_s12(mk12(590L, 64L, 413L)), &cells[2], 8299343UL, (short __far *)&cells[3]); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p7)((unsigned char)152, id_s12(mk12(590L, 64L, 413L)), &cells[2], 8299343UL, (short __far *)&cells[3]); report(r.a + r.b * 5L + r.c); }
    report((long)(f8((short)8700, (unsigned short)39600, id_f32(73.5f))));
    report((long)((*p8)((short)8700, (unsigned short)39600, id_f32(73.5f))));
    report((long)(f9(id_s12(mk12(660L, 71L, 462L)))));
    report((long)((*p9)(id_s12(mk12(660L, 71L, 462L)))));
    { struct S8 r = f10(id_i8((signed char)23), 2600080L, &cells[7], mk4(94, 95)); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p10)(id_i8((signed char)23), 2600080L, &cells[7], mk4(94, 95)); report(r.a + r.b * 5L + r.c); }
    { struct S12 r = f11(mk12(800L, 85L, 560L), mk8(87000L, 87, 89), id_f64(282.25), (unsigned short)600); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p11)(mk12(800L, 85L, 560L), mk8(87000L, 87, 89), id_f64(282.25), (unsigned short)600); report(r.a ^ r.b ^ r.c); }
    report((long)(f12(&cells[7], 3580094L, (long long)-38999997LL * 1000LL, 8.5f, id_i16((short)-4500), id_u16((unsigned short)13200))));
    report((long)((*p12)(&cells[7], 3580094L, (long long)-38999997LL * 1000LL, 8.5f, id_i16((short)-4500), id_u16((unsigned short)13200))));
    report((long)(f13(mk12(940L, 99L, 658L), mk8(1000L, 1, 3), (signed char)-42, id_u8((unsigned char)115))));
    report((long)((*p13)(mk12(940L, 99L, 658L), mk8(1000L, 1, 3), (signed char)-42, id_u8((unsigned char)115))));
    f14((short __far *)&cells[4], id_i32(-2439992L), id_f64(45.25), 66.25, id_fp((short __far *)&cells[0]), 36.5f, id_s4(mk4(43, 44))); report(cells[6]);
    (*p14)((short __far *)&cells[4], id_i32(-2439992L), id_f64(45.25), 66.25, id_fp((short __far *)&cells[0]), 36.5f, id_s4(mk4(43, 44))); report(cells[6]);
    report((long)(f15((short __far *)&cells[3], (unsigned short)9000)));
    report((long)((*p15)((short __far *)&cells[3], (unsigned short)9000)));
    report((long)(f16(id_u16((unsigned short)9000), (short __far *)&cells[1], (short __far *)&cells[0], 36.5f, 10043L, (short)6000)));
    report((long)((*p16)(id_u16((unsigned short)9000), (short __far *)&cells[1], (short __far *)&cells[0], 36.5f, 10043L, (short)6000)));
    report((long)(f17(mk4(22, 23), &cells[5], 4599676UL, id_fp((short __far *)&cells[6]), 150.25, (unsigned short)34200)));
    report((long)((*p17)(mk4(22, 23), &cells[5], 4599676UL, id_fp((short __far *)&cells[6]), 150.25, (unsigned short)34200)));
    { struct S12 r = f18((unsigned char)129, mk12(360L, 41L, 252L), (signed char)-7, mk4(50, 51), id_u16((unsigned short)34200)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p18)((unsigned char)129, mk12(360L, 41L, 252L), (signed char)-7, mk4(50, 51), id_u16((unsigned short)34200)); report(r.a ^ r.b ^ r.c); }
    report((long)(f19((unsigned char)136, id_u32(5299613UL), id_i16((short)6000))));
    report((long)((*p19)((unsigned char)136, id_u32(5299613UL), id_i16((short)6000))));
    report((long)(f20(id_i8((signed char)-7), (signed char)0, 6699487UL, mk4(64, 65), id_u8((unsigned char)171), 2460078L, mk4(85, 86))));
    report((long)((*p20)(id_i8((signed char)-7), (signed char)0, 6699487UL, mk4(64, 65), id_u8((unsigned char)171), 2460078L, mk4(85, 86))));
    report((long)*f21((signed char)0, 6699487UL, 1480064L, id_u32(8099361UL), (short)14400));
    report((long)*(*p21)((signed char)0, 6699487UL, 1480064L, id_u32(8099361UL), (short)14400));
    { struct S4 r = f22(mk12(570L, 62L, 399L), id_s12(mk12(640L, 69L, 448L)), &cells[7], (short __far *)&cells[1], id_s12(mk12(850L, 90L, 595L)), (unsigned char)192); report(r.a * 3L + r.b); }
    { struct S4 r = (*p22)(mk12(570L, 62L, 399L), id_s12(mk12(640L, 69L, 448L)), &cells[7], (short __far *)&cells[1], id_s12(mk12(850L, 90L, 595L)), (unsigned char)192); report(r.a * 3L + r.b); }
    report((long)(f23(id_f32(64.5f), id_i32(1970071L), id_i16((short)14400))));
    report((long)((*p23)(id_f32(64.5f), id_i32(1970071L), id_i16((short)14400))));
    report((long)(f24(id_np(&cells[7]), (short)14400, 9499235UL, &cells[4], id_i8((signed char)49), 1599946UL)));
    report((long)((*p24)(id_np(&cells[7]), (short)14400, 9499235UL, &cells[4], id_i8((signed char)49), 1599946UL)));
    f25(id_i16((short)14400), id_u32(9499235UL), mk8(92000L, 92, 94), id_s8(mk8(99000L, 99, 101)), 1599946UL, id_i32(-2089987L), id_np(&cells[4])); report(cells[1]);
    (*p25)(id_i16((short)14400), id_u32(9499235UL), mk8(92000L, 92, 94), id_s8(mk8(99000L, 99, 101)), 1599946UL, id_i32(-2089987L), id_np(&cells[4])); report(cells[1]);
    report((long)(f26(id_u16((unsigned short)51000), (long long)52000276LL * 1000LL, id_u16((unsigned short)59400), (unsigned char)106, (signed char)-37, (signed char)-30, (signed char)-23)));
    report((long)((*p26)(id_u16((unsigned short)51000), (long long)52000276LL * 1000LL, id_u16((unsigned short)59400), (unsigned char)106, (signed char)-37, (signed char)-30, (signed char)-23)));
    report((long)*f27(&cells[4], id_fp((short __far *)&cells[6])));
    report((long)*(*p27)(&cells[4], id_fp((short __far *)&cells[6])));
    report((long)(f28()));
    report((long)((*p28)()));
    report((long)(f29(&cells[6], (unsigned short)7800, id_u32(2999820UL), id_i8((signed char)-23), (unsigned char)134, mk12(410L, 46L, 287L), 144.25)));
    report((long)((*p29)(&cells[6], (unsigned short)7800, id_u32(2999820UL), id_i8((signed char)-23), (unsigned char)134, mk12(410L, 46L, 287L), 144.25)));
    report((long)(f30((short __far *)&cells[0], (unsigned short)12000, id_f32(27.5f), id_u16((unsigned short)20400), (unsigned short)24600, id_f32(48.5f))));
    report((long)((*p30)((short __far *)&cells[0], (unsigned short)12000, id_f32(27.5f), id_u16((unsigned short)20400), (unsigned short)24600, id_f32(48.5f))));
    report((long)(f31(id_i8((signed char)-30), id_u16((unsigned short)16200), (long long)-5999898LL * 1000LL, id_f32(41.5f), (unsigned short)28800, id_fp((short __far *)&cells[2]), id_i64((long long)22000186LL * 1000LL))));
    report((long)((*p31)(id_i8((signed char)-30), id_u16((unsigned short)16200), (long long)-5999898LL * 1000LL, id_f32(41.5f), (unsigned short)28800, id_fp((short __far *)&cells[2]), id_i64((long long)22000186LL * 1000LL))));
    { struct S8 r = f32(id_f32(27.5f), (unsigned short)20400, id_i8((signed char)-9)); report(r.a + r.b * 5L + r.c); }
    { struct S8 r = (*p32)(id_f32(27.5f), (unsigned short)20400, id_i8((signed char)-9)); report(r.a + r.b * 5L + r.c); }
    f33(id_i32(-619966L), (unsigned short)24600, 144.25, id_u16((unsigned short)33000)); report(cells[1]);
    (*p33)(id_i32(-619966L), (unsigned short)24600, 144.25, id_u16((unsigned short)33000)); report(cells[1]);
    { struct S4 r = f34((long long)1000123LL * 1000LL, id_s12(mk12(480L, 53L, 336L)), 850055L); report(r.a * 3L + r.b); }
    { struct S4 r = (*p34)((long long)1000123LL * 1000LL, id_s12(mk12(480L, 53L, 336L)), 850055L); report(r.a * 3L + r.b); }
    report((long)(f35((signed char)-2, id_u32(6499505UL), &cells[6], (unsigned char)169, &cells[4])));
    report((long)((*p35)((signed char)-2, id_u32(6499505UL), &cells[6], (unsigned char)169, &cells[4])));
    report((long)(f36()));
    report((long)((*p36)()));
    { long long r = f37((unsigned char)162, (long long)29000207LL * 1000LL, id_u16((unsigned short)45600), mk12(830L, 88L, 581L), &cells[2], id_i16((short)20100)); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    { long long r = (*p37)((unsigned char)162, (long long)29000207LL * 1000LL, id_u16((unsigned short)45600), mk12(830L, 88L, 581L), &cells[2], id_i16((short)20100)); report((long)(r % 1000003LL)); report((long)(r >> 20)); }
    report((long)(f38(id_fp((short __far *)&cells[0]), 76.5f, mk8(83000L, 83, 85), (short __far *)&cells[5])));
    report((long)((*p38)(id_fp((short __far *)&cells[0]), 76.5f, mk8(83000L, 83, 85), (short __far *)&cells[5])));
    report((long)(f39(228.25, id_u16((unsigned short)49800), (short __far *)&cells[5], id_s8(mk8(97000L, 97, 99)), id_fp((short __far *)&cells[7]), mk8(11000L, 11, 13))));
    report((long)((*p39)(228.25, id_u16((unsigned short)49800), (short __far *)&cells[5], id_s8(mk8(97000L, 97, 99)), id_fp((short __far *)&cells[7]), mk8(11000L, 11, 13))));
    report((long)(f40(id_i64((long long)43000249LL * 1000LL), 90.5f, (unsigned char)197, id_s12(mk12(40L, 9L, 28L)), -2229989L)));
    report((long)((*p40)(id_i64((long long)43000249LL * 1000LL), 90.5f, (unsigned char)197, id_s12(mk12(40L, 9L, 28L)), -2229989L)));
    report((long)*f41((signed char)40, id_i64((long long)57000291LL * 1000LL), &cells[4]));
    report((long)*(*p41)((signed char)40, id_i64((long long)57000291LL * 1000LL), &cells[4]));
    report((long)(f42(id_fp((short __far *)&cells[4]), id_s12(mk12(40L, 9L, 28L)), (signed char)-39, id_s12(mk12(180L, 23L, 126L)))));
    report((long)((*p42)(id_fp((short __far *)&cells[4]), id_s12(mk12(40L, 9L, 28L)), (signed char)-39, id_s12(mk12(180L, 23L, 126L)))));
    report((long)(f43(&cells[4], id_f32(11.5f), mk4(18, 19), (long long)-14999925LL * 1000LL, (long long)-7999904LL * 1000LL, (unsigned short)23400, id_s8(mk8(46000L, 46, 48)))));
    report((long)((*p43)(&cells[4], id_f32(11.5f), mk4(18, 19), (long long)-14999925LL * 1000LL, (long long)-7999904LL * 1000LL, (unsigned short)23400, id_s8(mk8(46000L, 46, 48)))));
    f44(id_i16((short)-5700), (signed char)-32, id_np(&cells[1])); report(cells[4]);
    (*p44)(id_i16((short)-5700), (signed char)-32, id_np(&cells[1])); report(cells[4]);
    { struct S12 r = f45(id_u8((unsigned char)118), (long long)-14999925LL * 1000LL, mk8(32000L, 32, 34), id_s8(mk8(39000L, 39, 41))); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p45)(id_u8((unsigned char)118), (long long)-14999925LL * 1000LL, mk8(32000L, 32, 34), id_s8(mk8(39000L, 39, 41))); report(r.a ^ r.b ^ r.c); }
    { struct S4 r = f46(id_u16((unsigned short)15000), 96.25, (signed char)-11, (unsigned short)27600, id_i16((short)6900), id_fp((short __far *)&cells[7])); report(r.a * 3L + r.b); }
    { struct S4 r = (*p46)(id_u16((unsigned short)15000), 96.25, (signed char)-11, (unsigned short)27600, id_i16((short)6900), id_fp((short __far *)&cells[7])); report(r.a * 3L + r.b); }
    report((long)(f47(mk12(320L, 37L, 224L), id_f64(117.25), id_s8(mk8(46000L, 46, 48)), mk8(53000L, 53, 55), 60.5f)));
    report((long)((*p47)(mk12(320L, 37L, 224L), id_f64(117.25), id_s8(mk8(46000L, 46, 48)), mk8(53000L, 53, 55), 60.5f)));
    { struct S12 r = f48(id_i8((signed char)-11), id_u8((unsigned char)146), (signed char)3, mk4(60, 61), &cells[3], (unsigned char)174, id_f32(81.5f)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p48)(id_i8((signed char)-11), id_u8((unsigned char)146), (signed char)3, mk4(60, 61), &cells[3], (unsigned char)174, id_f32(81.5f)); report(r.a ^ r.b ^ r.c); }
    report((long)(f49(&cells[6], id_s8(mk8(53000L, 53, 55)), id_i16((short)9000), id_i8((signed char)17))));
    report((long)((*p49)(&cells[6], id_s8(mk8(53000L, 53, 55)), id_i16((short)9000), id_i8((signed char)17))));
    report((long)(f50(mk8(53000L, 53, 55))));
    report((long)((*p50)(mk8(53000L, 53, 55))));
    { struct S12 r = f51(); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p51)(); report(r.a ^ r.b ^ r.c); }
    report((long)(f52(id_s12(mk12(670L, 72L, 469L)), id_u8((unsigned char)174), id_u8((unsigned char)181), 264.25, 95.5f)));
    report((long)((*p52)(id_s12(mk12(670L, 72L, 469L)), id_u8((unsigned char)174), id_u8((unsigned char)181), 264.25, 95.5f)));
    report((long)(f53(mk8(74000L, 74, 76), 2670081L, (long long)48000264LL * 1000LL)));
    report((long)((*p53)(mk8(74000L, 74, 76), 2670081L, (long long)48000264LL * 1000LL)));
    report((long)(f54(mk12(810L, 86L, 567L), id_i64((long long)48000264LL * 1000LL), (unsigned char)195, (unsigned char)102, (unsigned char)109, &cells[0], id_s8(mk8(23000L, 23, 25)))));
    report((long)((*p54)(mk12(810L, 86L, 567L), id_i64((long long)48000264LL * 1000LL), (unsigned char)195, (unsigned char)102, (unsigned char)109, &cells[0], id_s8(mk8(23000L, 23, 25)))));
    { struct S12 r = f55(id_f64(264.25), id_i64((long long)55000285LL * 1000LL), (long long)-37999994LL * 1000LL, mk12(90L, 14L, 63L), mk4(16, 17)); report(r.a ^ r.b ^ r.c); }
    { struct S12 r = (*p55)(id_f64(264.25), id_i64((long long)55000285LL * 1000LL), (long long)-37999994LL * 1000LL, mk12(90L, 14L, 63L), mk4(16, 17)); report(r.a ^ r.b ^ r.c); }
    { struct S4 r = f56((unsigned char)195, id_fp((short __far *)&cells[5]), id_u16((unsigned short)5400), (short __far *)&cells[3], -1389977L, mk12(300L, 35L, 210L), 37.5f); report(r.a * 3L + r.b); }
    { struct S4 r = (*p56)((unsigned char)195, id_fp((short __far *)&cells[5]), id_u16((unsigned short)5400), (short __far *)&cells[3], -1389977L, mk12(300L, 35L, 210L), 37.5f); report(r.a * 3L + r.b); }
    report((long)(f57(mk8(2000L, 2, 4))));
    report((long)((*p57)(mk8(2000L, 2, 4))));
    report((long)(f58(1899919UL, id_s12(mk12(160L, 21L, 112L)))));
    report((long)((*p58)(1899919UL, id_s12(mk12(160L, 21L, 112L)))));
    report((long)(f59(mk4(16, 17), (short)-2100)));
    report((long)((*p59)(mk4(16, 17), (short)-2100)));
    return 0;
}
